---
title: "skin-pigmentation-1"
author: "Ben Zydney"
date: "2022-02-17"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
library(readxl)
SkinData <- read_excel("data/SkinData.xlsx", 
    sheet = "SkinData", col_types = "guess")

library(ggplot2)
library(reshape2)


start = 1
end = 99999

# 2 is ID
# 16 - 46 are wavelengths
# 48 is MID

SkinDF <- SkinData[SkinData$Loc. != "H", ][start:end , 16:36]


df <- melt(SkinDF) # Turn the wavelengths into a long format

colnames(df)[1] <- "wavelengths"
colnames(df)[2] <- "reflectance"
df$wavelengths = as.integer(sub('.', '', as.character(df$wavelengths)))


df$ID <- SkinData$ID[start:end]
df$MI <- SkinData$MI...48[start:end]
df$CEU <- SkinData$CEU[start:end]
df$CHB <- SkinData$CHB[start:end]
df$YRI <- SkinData$YRI[start:end]
df$Bat <- SkinData$Bat[start:end]

threshold = 0.95

df$category <- 
  ifelse(df$CEU > threshold, 'Europe', 
  ifelse(df$CHB > threshold, 'Han Chinese', 
  ifelse(df$YRI > threshold, 'Yoruba', 
  ifelse(df$YRI + df$CEU > threshold, 'Yoruba and Europe', NA))))


filtered_df <- df[!is.na(df$category),]


ggplot(filtered_df, aes(wavelengths, reflectance, group=Bat, color=MI)) + 
  geom_line() +
  facet_wrap(~category, ncol = 2) +
  scale_color_distiller(palette = 'YlOrRd') +
  expand_limits(y = 0)

```

All of the gray is from data that has no MI in the spreadsheet.

The much lower ones seem to come from location H (is that head?) should we filter those out?

```{r}
filtered_df <- filtered_df[!is.na(filtered_df$MI),]
ggplot(filtered_df, aes(wavelengths, reflectance, group=Bat, color=MI)) + 
  geom_line() +
  facet_wrap(~category, ncol = 2) +
  scale_color_distiller(palette = 'YlOrRd') +
  expand_limits(y = 0)

```

If we were to reduce the threshold down to 0.75:

```{r}
threshold = 0.75

df$category <- 
  ifelse(df$CEU > threshold, 'Europe', 
  ifelse(df$CHB > threshold, 'Han Chinese', 
  ifelse(df$YRI > threshold, 'Yoruba', 
  ifelse(df$YRI + df$CEU > threshold, 'Yoruba and Europe', NA))))

filtered_df <- df[!is.na(df$category),]
filtered_df <- filtered_df[!is.na(filtered_df$MI),]


ggplot(filtered_df, aes(wavelengths, reflectance, group=Bat, color=MI)) + 
  geom_line() +
  facet_wrap(~category, ncol = 2) +
  scale_color_distiller(palette = 'YlOrRd') +
  expand_limits(y = 0)
```


Finally, if we were to reduce the threshold down to just 0.6:

```{r}
threshold = 0.75

df$category <- 
  ifelse(df$CEU > threshold, 'Europe', 
  ifelse(df$CHB > threshold, 'Han Chinese', 
  ifelse(df$YRI > threshold, 'Yoruba', 
  ifelse(df$YRI + df$CEU > threshold, 'Yoruba and Europe', NA))))

filtered_df <- df[!is.na(df$category),]
filtered_df <- filtered_df[!is.na(filtered_df$MI),]


ggplot(filtered_df, aes(wavelengths, reflectance, group=Bat, color=MI)) + 
  geom_line() +
  facet_wrap(~category, ncol = 2) +
  scale_color_distiller(palette = 'YlOrRd') +
  expand_limits(y = 0)
```

