---
title: "Skin Reflectance"
author: "Tina Lasisi"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  workflowr::wflow_html:
    toc: yes
    number_sections: yes
editor_options:
  chunk_output_type: console
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(tidyverse)
library(knitr)
library(scales)
library(patchwork)
library(ggbeeswarm)
library(ggridges)
library(ggmulti)
library(paletteer)
library("stringr")

# knitting to pdf
# rmarkdown::render(input = "analysis/analysis.Rmd", output_format = "pdf_document", output_dir = "output")
F = rprojroot::is_rstudio_project$make_fix_file()
palettedf <- tibble(paletteer::palettes_d_names)
# filter(.data = palettedf, length > 10 & type == "qualitative")
knitr::opts_chunk$set(echo = FALSE, include = TRUE, eval = TRUE, warning = FALSE, message = FALSE, fig.retina = 2, fig.width = 8, fig.height = 6, out.width = "100%")


# skin <- read_csv(F("data/complete_skin_data.csv")) %>% 
#   mutate(l = factor(`Loc.`, levels = c("F","R", "L", "H"))) %>% 
#   pivot_longer(starts_with("W"), names_to = "wavelength", values_to = "reflectance")%>% 
#   mutate(wavelength = as.numeric(str_remove(wavelength, "\\D+")),
#          CMI = as.numeric(CMI)) %>% 
#   mutate(population = factor(case_when(CEU >= 0.95 ~ "European",
#                           CHB + GIH + JPT >= 0.95 ~ "Asian",
#                           YRI + LWK + MKK >= 0.95 ~ "African",
#                           YRI + CEU + TSI + YRI + MKK >= 0.95 ~ "African-European",
#                           TRUE ~ "Other"))) %>% 
#   select(ID, l, "MI", "CMI", wavelength, reflectance, population) %>% 
#   rename(id = ID, mi = MI, cmi = CMI)

```


```{r functions, eval=FALSE, include=FALSE}
# This is a function to save the figures
plot_path = F("output/")
pltsave_func <- function(plot, plot_path, width, height){
  ggsave(
      filename = paste0(deparse(substitute(plot)), ".png"),
      plot = plot, 
      path = plot_path,
      width = width,
      height = height)
  plot(plot)
}
```

```{r df-import, include=FALSE}
# Importing data

# skin <- read_csv(F("data/forr_reflectance.csv"), 
#     col_types = cols(l = col_factor(levels = c("F", 
#         "R", "L", "H")), fp = col_factor(levels = c("South_Asian", 
#         "East_Asian", "Northern_European", 
#         "Southern European", "Afr_Eur", "African"))))


skin <- read_csv(F("data/forr_reflectance.csv")) %>% 
  mutate(l = factor(l, levels = c("F","R", "L", "H")),
         fp = factor(fp, levels = c("South_Asian", "East_Asian", "Northern_European", "Southern European", "Afr_Eur", "African")))

head(skin)

```


```{r df-pivot, include=FALSE}

skin_long <- pivot_longer(skin, starts_with("W"), names_to = "wavelength", values_to = "reflectance")%>% 
  mutate(wavelength = as.numeric(str_remove(wavelength, "\\D+")),
         population = fct_collapse(fp, Asian = c("South_Asian", "East_Asian"),
                                   European = c("Northern_European", "Southern European"))) %>% 
  filter(id != 143632 & id !=143334)


skin_long

```

```{r df-filter}

df_plot <- skin_long %>%
  drop_na() %>%
  filter(reflectance>2 & l == "F") %>% 
  group_by(id, population, wavelength) %>% 
  mutate(median = median(reflectance)) %>% 
  mutate(mean = mean(reflectance)) %>% 
  mutate(fitz = case_when(cmi <= 25 & population == "European" ~ "Type 1",
                          cmi <= 30 & population == "European" ~ "Type 2",
                          cmi <= 35 & population == "European" ~ "Type 3",
                          cmi <= 40 ~ "Type 4",
                          cmi <= 80 ~ "Type 5",
                          TRUE ~ "Type 6"),
         fitz = factor(fitz, levels = c("Type 1", "Type 2", "Type 3", "Type 4", "Type 5", "Type 6"))) %>% 
  distinct(id,cmi, .keep_all = TRUE)
  
```

```{r count}

df_plot %>% 
  ungroup() %>% 
  summarise(count = n_distinct(id))
```

```{r plt-skin}

table(df_plot$population)


population_labels <- c(
  Asian = ">95% Asian (n = 71)",
  African = ">95% African (n = 25)",
  Afr_Eur = ">95% combined European-African (n = 110)",
  European = ">95% European (n = 171)"
)
library(dplyr)


ggplot(df_plot, aes(wavelength, median, group=id, color=cmi)) +
# ggplot(df_plot, aes(wavelength, mean, group=id, color=cmi)) + 
  geom_line() +
  facet_wrap(~population, ncol = 2, labeller = labeller(population = population_labels)) +
  # scale_color_gradient2(low = "blue", high = "red", mid = "cyan")
  # scale_color_gradient(low = "#f7eed7", high = "#42230c") +
  # scale_color_distiller(palette = 'YlOrRd') +
  scale_color_gradientn(colours = c("#42230c", "#a15c33" , "#fbf7ec"),
                        values = rescale(x= c(50, 40, 20)),
                        oob = squish,
                        limits = c(20, 100)) +
  expand_limits(y = 0) +
  theme_classic() +
  
  ylab("Percent Reflectance of Skin") +
  xlab("Wavelength") +
  guides(color = guide_colorbar(reverse = TRUE)) +
  labs(color = "Melanin Index") +
    annotate("rect", xmin = 640, xmax = 670, ymin = 0, ymax =70, 
           alpha = 0.3, fill = "#ff0000")
  

```

```{r df-hist}
# df_plot %>% 
#   group_by(population) %>% 
#   summarise(min = min(cmi), max = max(cmi))
  
df_hist <- df_plot %>% 
  ungroup() %>% 
  select(-c(wavelength, reflectance)) %>% 
  distinct(id, cmi, .keep_all = TRUE) %>% 
  group_by(population)

```


```{r plt-hist, fig.height=3, fig.width=5}
# regular histogram - melanin index
ggplot(df_hist, aes(x=cmi, fill=population, color=population)) +
  geom_histogram(position="identity", alpha=0.5) +
  theme_classic()

# regular histogram fitzpatrick scale
ggplot(df_hist, aes(x=fitz, fill=population, color=population)) +
  geom_bar(alpha=0.5, position = position_dodge2(width=0.9, preserve = "single"), width = 1) +
  theme_classic() +
  xlab("Fitzpatrick Skin Phototype")

```

```{r hist-setup}
# Method for removing baseline color in a ggplot histogram from https://stackoverflow.com/questions/57128090/remove-baseline-color-for-geom-histogram
StatBin2 <- ggproto(
  "StatBin2", 
  StatBin,
  compute_group = function (data, scales, binwidth = NULL, bins = NULL, 
                            center = NULL, boundary = NULL, 
                            closed = c("right", "left"), pad = FALSE, 
                            breaks = NULL, origin = NULL, right = NULL, 
                            drop = NULL, width = NULL) {
    if (!is.null(breaks)) {
      if (!scales$x$is_discrete()) {
        breaks <- scales$x$transform(breaks)
      }
      bins <- ggplot2:::bin_breaks(breaks, closed)
    }
    else if (!is.null(binwidth)) {
      if (is.function(binwidth)) {
        binwidth <- binwidth(data$x)
      }
      bins <- ggplot2:::bin_breaks_width(scales$x$dimension(), binwidth, 
                                         center = center, boundary = boundary, 
                                         closed = closed)
    }
    else {
      bins <- ggplot2:::bin_breaks_bins(scales$x$dimension(), bins, 
                                        center = center, boundary = boundary, 
                                        closed = closed)
    }
    res <- ggplot2:::bin_vector(data$x, bins, weight = data$weight, pad = pad)

    # Only drop the bars if they are not in between others
    res <- res[res$x <= max(res[res$count > 0, "x"]), ]
    res <- res[res$x >= min(res[res$count > 0, "x"]), ]
               
    res
  })
```

```{r df-hist-facet, fig.height=4, fig.width=8}
# df_plot %>% 
#   group_by(population) %>% 
#   summarise(min = min(cmi), max = max(cmi))
  
# regular histogram fitzpatrick scale
p1 <- ggplot(df_hist, aes(x=fitz, fill=population, color=population)) +
  geom_bar(alpha=0.5, width = 1) +
  theme_classic()+ facet_grid(population ~., scales = "free") +
  xlab("Fitzpatrick Skin Phototype") +
  ylab("Count") +

  theme(
    strip.background = element_blank(),
    strip.text.y = element_blank(),
    # legend.position = "left"
    legend.position = "none"
  ) 
  #  scale_fill_discrete(name = "Test", labels = c(">95% Asian", ">95% African",">95% combined\nEuropean-African", ">95% European")) +
  # guides(fill=guide_legend("Ancestry"),color='none')

supp.labs <- c("Asian\n(n = 71)", "European\n(n = 171)","European-African\n(n = 110)", "African\n(n = 25)")
names(supp.labs) <-c("Asian", "European", "Afr_Eur", "African")

   
# regular histogram - melanin index
p2 <- ggplot(df_hist, aes(x=cmi, fill=population, color=population)) +
  geom_histogram(position="identity", alpha=0.5, binwidth = 5, stat = StatBin2) +
  theme_classic() + 
  facet_grid(population ~., scales = "free", 
             labeller = labeller(population = supp.labs)) +
   # geom_hline(yintercept=0, colour="white", size=1) +
  xlab("Melanin Index") +
  theme(
    # strip.background = element_blank(),
    # strip.text.y = element_blank(),
    # axis.title.y = element_blank(),
    # legend.title = element_blank(),
    # legend.margin=margin(t=0,l=-0.5,b=0.0,r=0, unit='cm'),
    # legend.spacing.y = unit(0.3, 'cm')
    # strip.text.y = element_text(angle = 0),
    legend.position = "none"
  ) 


g <- ggplot_gtable(ggplot_build(p2))
stripr <- which(grepl('strip-r', g$layout$name))
fills <- c("#F8766D", "#7CAE00", "#00BFC4", "#C77CFF")
k <- 1
for (i in stripr) {
j <- which(grepl('rect', g$grobs[[i]]$grobs[[1]]$childrenOrder))
g$grobs[[i]]$grobs[[1]]$children[[j]]$gp$fill <- fills[k]
k <- k+1
}

p2 <- g
# grid::grid.draw(g)

# plot(g)

# regular histogram fitzpatrick scale
# p1 <- ggplot(df_hist, aes(x=as.numeric(fitz), fill=population, color=population)) +
#   geom_histogram(position="identity", alpha=0.5, bins = 6) +
#   theme_classic()+ facet_grid(population ~., scales = "free") +
#   theme(legend.position = "none") +
#   xlab("Melanin Index") +
#   labs(color = "Ancestry", fill = "Ancestry")

p1 + p2


```

```{r df-hist-multi, eval=FALSE, include=FALSE}
# Density 

# Histogram by Melanin index grouped by fitzpatrick
ggplot(df_hist, 
            mapping = aes(x = fitz, 
                          y = cmi, 
                          fill = population)) + 
  geom_histogram_(as.mix = FALSE,
                  scale.y = "group",
                  alpha = 0.5,
                  # binwidth = 5,
                  prop = 0.8) + 
  labs(caption = "Figure 2") +
  theme_classic()


# histogram by melanin index grouped by population

g <- df_hist %>% 
  mutate(population = fct_reorder(population, cmi, .fun = "max")) %>% 
  ggplot(., 
            mapping = aes(x = reorder(population, cmi), 
                          y = cmi, 
                          fill = fitz)) + 
  geom_histogram_(as.mix = FALSE,
                  scale.y = "group",
                  alpha = 0.5,
                  # binwidth = 5,
                  prop = 0.8) + 
  labs(caption = "Figure 2") +
  theme_classic()

g + geom_density_(as.mix = FALSE, 
                positive = FALSE, 
                alpha = 0.5,
                scale.y = "group",
                postition = "stack_",
                prop = 0.9) + 
  labs(caption = "Figure 3") +
  coord_flip() +
  theme_classic()


ggplot(df_hist,
              mapping = aes(x = cmi, fill = population)) + 
  # it is equivalent to call `geom_density()`
  geom_density_(alpha = 0.3) + 
  scale_fill_brewer(palette = "Set3") + 
  labs(caption = "Figure 4") +
  theme_classic()

```


```{r df-dot, eval=FALSE, include=FALSE}

# by population on x axis

df_hist %>% 
  mutate(population = fct_reorder(population, cmi, .fun = "max")) %>% 
  ggplot(., 
            mapping = aes(x = reorder(population, cmi), 
                          y = cmi, 
                          fill = fitz,
                          color = fitz)) +
  geom_boxplot(width = 0.7, 
               size = 0.4,
               alpha = 0.1,
               position = position_dodge(0.8)
               ) +
  geom_quasirandom(dodge = 0.7,
                   show.legend = TRUE,
                   alpha = 0.8) +
  # geom_point(position = position_jitterdodge(), alpha=0.1)+
  theme_classic()


# by fitzpatrick on x axis

df_hist %>% 
  ggplot(., 
            mapping = aes(x = fitz, 
                          y = cmi, 
                          fill = population,
                          color = population)) +
  geom_boxplot(width = 0.5, 
               size = 0.4,
               alpha = 0.1,
               position = position_dodge(0.8)
               ) +
  # geom_jitter() +
  geom_quasirandom(dodge = 0.7,
                   show.legend = TRUE,
                   alpha = 0.4) +
  theme_classic()


```

```{r eval=FALSE, include=FALSE}
df_hist %>% 
  mutate(population = fct_reorder(population, cmi, .fun = "max")) %>% 
  ggplot(., 
            mapping = aes(x = reorder(population, cmi), 
                          y = cmi, 
                          fill = fitz,
                          color = fitz)) +
  geom_boxplot(width = 0.5, 
               size = 0.4,
               alpha = 0.1,
               position = position_dodge(0.8)
               ) +
  geom_point(position = position_jitterdodge()) +
  geom_quasirandom(dodge = 0.7,
                   show.legend = TRUE,
                   alpha = 0.1,
                   size = 0.001) +
  theme_classic()+
labs(x = "...", y = "...") 
```


```{r, eval=FALSE, include=FALSE}

# ridge plot

ggplot(df_hist, 
       aes(x = cmi, 
           y = fitz, 
           fill = population)) +
  geom_density_ridges(alpha = 0.4, scale = 1) + 
  theme_ridges()

```

```{r, eval=FALSE, include=FALSE}

# ridge plot

ggplot(df_hist, 
       aes(x = cmi, 
           y = fitz, 
           fill = population)) +
  geom_violin()

```

